baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'CDED Recipes'

theme = "archie"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All recipes"
url = "/recipes"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3
